### ISSUE TITLE
Allowing saved reference and temporary practice to be displayed from storage

### ISSUE THREAD

**Issue by shreyapandit** [ExerciseCheck/electron-enabled-app#66]
- [x] Display Ref on landing page
- [x] Display reference on a separate canvas when mode is play
- [x] Replay saved dataframes from localStorage when user clicks stop
- [x] Add green circle check
- [x] Fix canvas resolution to be same as the previous codebase
- [x] In the play mode, start rendering of reference only when current user is aligned with green circle

**Comment by zsqiii** [comment]
Resolution Fixed

**Comment by zsqiii** [comment]
Done!
                                        - siqi and Shirene

**Comment by shreyapandit** [comment]
Merged as part of #77
