### ISSUE TITLE
Get over Reps code into anchor

### ISSUE THREAD

**Issue by shreyapandit** [ExerciseCheck/electron-enabled-app#67]
- 2 joints for amplitude, one for tracking, thats ref_max
- Bottom threshold at top of kinect axis.
- ref_neck coordinate also on most imp axis
- same with ref points for both imp joints
- Save neck only when hit circle. Irrespective of exercise. in session
- Your reference in clinic,in green circle, neck and 2most imp joints x,y recorded

**Comment by shreyapandit** [comment]
This would also involve using DTW for analysis for a rep. reference should also be  = 1 repetition and we should ensure that during the first phase

**Comment by shreyapandit** [comment]
Notes from Shreya R's code:

- when a practice session starts, set a localstorage variable called reps with value as 0

- she calls countReps every time a new body is passed onto the canvas. Body is body with same tracingId for that user. @saurabh21289 we talked about this and we should implement it here so that its fixed. 

- [ ] Update exercise model with following params:
- Joint: most important joint for exercise
- Axis: most important axis for exercise. Should be depthY or depthX
- Direction: Initial direction for determining reps. Should be 'up' or 'down'
- ref_lower_joint is lower joint for exercise. Can be jointID
- ref_upper_joint is upper joint for exercise. Can be jointID

Please add model level validations with joi for that

- [ ] Update reference model with range_scale. Its a tolerance value between 0 and 1 deciding how much of the distance should be covered for one rep to be deemed as completed. Default to be range_scale=0.7
- [ ] Update reference model with a top_thresh and bottom_thresh which are values that are b/w 0 and 1 and considered for a complete rep. Default to be  top_thresh=0.25, bottom_thresh=0.75
- [ ] Add another field on ref properties page for that.

- [ ] When user saves a REFERENCE, update model with following parameters
- neck_x is  nx/width , neck_y = ny/height. when you 1st hit the green circle during your reference. Later, we will use the neck coordinate X/Y depending on most imp axis for that exercise 
- ref_max is max point from ref data recorded
-ref_min is min point from ref data recorded
- ref_lower_joint (called ref_foot in her code) is X,Y of the lower joint of exercise when you 1st hit the green circle during your reference. We will save X/Y based on whats the axis for this exercise.
- ref_upper_joint (called ref_spine in her code) is X,Y of the upper joint of exercise when you 1st hit the green circle during your reference. We will save X/Y based on whats the axis for this exercise.
- All these values can be calculated on the fly and saved in local storage and then saved along with reference data in model

Once all this is added, and saved, rendering

- [ ] Add a div for updating reps in session.handlebars
- [ ] Make sure session.handlebars has all the thresholds it requires from the ref and exercise models. The GET route should take care of this. Values can be added as hidden div having the values needed as a json.
- [ ] Take care of counting reps on receiving new bodyframe ONLY when the person has aligned in the green circle. Can have state saved in localstorage for the same.
- [ ] On each new bodyframe, init threshold_flag  from exercise info passed into template.call updateCanvas which calls countReps. Draw body should have reps and next direction. Store this in a local var, and update reps with count returned from updateCanvas

**Comment by EvenGu** [comment]
Thank you Shreya! That is helpful!

**Comment by shreyapandit** [comment]
@xin-cao will be adding fields to the models since she is changing them anyways. We can still do the UI in parallel by adding methods that calculate reps and save them in localstorage in parallel.
