### ISSUE TITLE
Add extra fields to create exercise page

### ISSUE THREAD

**Issue by shreyapandit** [ExerciseCheck/electron-enabled-app#78]
Will help in saving data required for #67 

Joint: most important joint for exercise.Should be a select box with options as name of joints and values as jointd

Axis: most important axis for exercise. Should be depthY or depthX

Direction: Initial direction for determining reps. Should be ‘up’ or ‘down’

ref_lower_joint is lower joint for exercise. Should be a select box with options as name of joints and values as jointd

ref_upper_joint is upper joint for exercise. Should be a select box with options as name of joints and values as jointd

**Comment by saurabh21289** [comment]
Added the additional fields to the UI:-
![image](https://user-images.githubusercontent.com/13815692/42531851-b216ee14-84a2-11e8-97fd-2814b6830213.png)
