### ISSUE TITLE
Model changes

### ISSUE THREAD

**Issue by shreyapandit** [ExerciseCheck/electron-enabled-app#80]
- Split userexercise model into ref and practice
- add extra fields to exercise, reference and practice.

Precursor to #67

**Comment by xin-cao** [comment]
Checklist copied from 67:

- [ ] Update exercise model with following params:
- Joint: most important joint for exercise
- Axis: most important axis for exercise. Should be depthY or depthX
- Direction: Initial direction for determining reps. Should be 'up' or 'down'
- ref_lower_joint is lower joint for exercise. Can be jointID
- ref_upper_joint is upper joint for exercise. Can be jointID

Please add model level validations with joi for that

- [ ] Update reference model with range_scale. Its a tolerance value between 0 and 1 deciding how much of the distance should be covered for one rep to be deemed as completed. Default to be range_scale=0.7
- [ ] Update reference model with a top_thresh and bottom_thresh which are values that are b/w 0 and 1 and considered for a complete rep. Default to be  top_thresh=0.25, bottom_thresh=0.75
- [ ] Add another field on ref properties page for that.

- [ ] When user saves a REFERENCE, update model with following parameters
- neck_x is  nx/width , neck_y = ny/height. when you 1st hit the green circle during your reference. Later, we will use the neck coordinate X/Y depending on most imp axis for that exercise 
- ref_min and ref_max, are X OR Y coordinates based on which axis is important for exercise, and are the MIN and MAX point throughout the reference signal?
- ref_lower_joint (called ref_foot in her code) is the is X OR Y coordinate of LOWER joint (foot in squat case) based on which axis is important for exercise. Calculated during reference when at the same instant when neck is aligned inside green circle.We will save X/Y based on whats the axis for this exercise.
- ref_upper_joint (called ref_spine in her code) is the is X OR Y coordinate of UPPER joint (spine in squat case) based on which axis is important for exercise. Calculated during reference when at the same instant when neck is aligned inside green circle. We will save X/Y based on whats the axis for this exercise.
- All these values can be calculated on the fly and saved in local storage and then saved along with reference data in model
- The ref_neck is X OR Y coordinate of neck joint based on which axis is important for exercise. Calculated during reference when neck is aligned inside green circle.

**Comment by shreyapandit** [comment]
PRACTICE:
* A practice exercise session needs to be completed in a single setting
* When they start a Practice session, always create a new practice record
* if a user wants to exit the session midway (after completing a set, or in middle of a set), we ask them if they want to leave with a prompt. If they choose yes, we update the wasCompleted flag for that practice exercise record to be false. Use window property `onbeforeunload `
* This way we store how many times they actually did the session in one go, and when did they do a complete one

REFERENCE:
* Each time the properties or the data is changed by a clinician, create a new reference exercise for that (exercise, patient) combination.
* Each practice session following that change should be linked to the new reference exercise, the reference loaded should be the most latest reference (exists in code but we should check)
